export const DB_NAME = 'dealFlow360';

export const USER_ROLES = Object.freeze({
    SALES_REP: 'SALES_REP',
    SALES_MANAGER: 'SALES_MANAGER',
    FINANCE: 'FINANCE',
    ADMIN: 'ADMIN',
    CUSTOMER: 'CUSTOMER'
});

export const INTERNAL_ROLES = Object.freeze([
    USER_ROLES.SALES_REP,
    USER_ROLES.SALES_MANAGER,
    USER_ROLES.FINANCE,
    USER_ROLES.ADMIN
]);

export const USER_STATUSES = Object.freeze({
    ACTIVE: 'ACTIVE',
    DISABLED: 'DISABLED'
});

export const CUSTOMER_STATUSES = Object.freeze({
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    ARCHIVED: 'ARCHIVED'
});

export const PRODUCT_STATUSES = Object.freeze({
    ACTIVE: 'ACTIVE',
    ARCHIVED: 'ARCHIVED'
});

export const PRODUCT_BILLING_TYPES = Object.freeze({
    ONE_TIME: 'ONE_TIME',
    RECURRING: 'RECURRING'
});

export const QUOTATION_STATUSES = Object.freeze({
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    RETURNED_FOR_REVISION: 'RETURNED_FOR_REVISION',
    APPROVED: 'APPROVED',
    SENT_TO_CUSTOMER: 'SENT_TO_CUSTOMER',
    READY_FOR_CUSTOMER: 'READY_FOR_CUSTOMER',
    UNDER_NEGOTIATION: 'UNDER_NEGOTIATION',
    REAPPROVAL_REQUIRED: 'REAPPROVAL_REQUIRED',
    NEGOTIATION: 'NEGOTIATION',
    CONFIRMED: 'CONFIRMED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED'
});

export const AUDIT_ACTIONS = Object.freeze({
    QUOTATION_CREATED: 'QUOTATION_CREATED',
    QUOTATION_LINE_ADDED: 'QUOTATION_LINE_ADDED',
    QUOTATION_LINE_CHANGED: 'QUOTATION_LINE_CHANGED',
    DISCOUNT_CHANGED: 'DISCOUNT_CHANGED',
    QUOTATION_SUBMITTED: 'QUOTATION_SUBMITTED',
    QUOTATION_SENT_TO_CUSTOMER: 'QUOTATION_SENT_TO_CUSTOMER',
    RISK_CALCULATED: 'RISK_CALCULATED',
    APPROVAL_CREATED: 'APPROVAL_CREATED',
    APPROVAL_APPROVED: 'APPROVAL_APPROVED',
    APPROVAL_REJECTED: 'APPROVAL_REJECTED',
    APPROVAL_RETURNED: 'APPROVAL_RETURNED',
    CUSTOMER_NEGOTIATION: 'CUSTOMER_NEGOTIATION',
    QUOTATION_CONFIRMED: 'QUOTATION_CONFIRMED',
    QUOTATION_VERSION_CREATED: 'QUOTATION_VERSION_CREATED',
    QUOTATION_STATE_CHANGED: 'QUOTATION_STATE_CHANGED'
});

export const NEGOTIATION_MESSAGE_TYPES = Object.freeze({
    LINE_QUESTION: 'LINE_QUESTION',
    QUANTITY_CHANGE: 'QUANTITY_CHANGE',
    PRICE_CHANGE: 'PRICE_CHANGE',
    COUNTER_DISCOUNT: 'COUNTER_DISCOUNT',
    GENERAL_COMMENT: 'GENERAL_COMMENT'
});

export const APPROVAL_STATUSES = Object.freeze({
    NOT_REQUIRED: 'NOT_REQUIRED',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    RETURNED: 'RETURNED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED'
});

export const APPROVAL_STEP_STATUSES = Object.freeze({
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    APPROVED: 'APPROVED',
    RETURNED: 'RETURNED',
    REJECTED: 'REJECTED',
    SKIPPED: 'SKIPPED'
});
