export const ErrorCodes = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    INVALID_SHIPMENT_QTY: 'INVALID_SHIPMENT_QTY',
    DUPLICATE_BILLING_PERIOD: 'DUPLICATE_BILLING_PERIOD',
    PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
};
